name: dart_melty_soundfont
description: A Soundfont synthesizer (i.e. '.sf2' player) written in pure Dart.
version: 3.1.0
homepage: https://github.com/sonofield/sf2_renderer


environment:
  sdk: '>=3.3.3 <4.0.0'
