name: sf2_renderer
description: A Soundfont synthesizer (i.e. '.sf2' player) written in pure Dart.
version: 3.0.1
homepage: https://github.com/sonofield/sf2_renderer


environment:
  sdk: '>=3.3.3 <4.0.0'
