name: dart_melty_soundfont
description: A Soundfont synthesizer (i.e. '.sf2' player) written in pure Dart.
version: 3.0.1
homepage: https://github.com/chipweinberger/dart_melty_soundfont


environment:
  sdk: '>=3.3.3 <4.0.0'
